---
version: '3.9'
services:
  file_browser:
    image: hurlenko/filebrowser
    user: "1000:1000"
    ports:
      - 8188:8080
    volumes:
      - /:/data
      - /app/filebrowser/config:/config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "100"
    environment:
      VIRTUAL_HOST: filebrowser.arpa
      VIRTUAL_PORT: 8188
