---
version: '3.9'
services:
  file_browser:
    image: hurlenko/filebrowser
    user: "1000:1000"
    ports:
      - 8188:8080
    command: --config=/config/app/filebrowser.json --database=/config/filebrowser.db --address=0.0.0.0 --port=8080 --log=/config/log/filebrowser.log
    healthcheck:
      test: curl -f http://localhost:8080/health || exit 1
    volumes:
      - /:/data:z
      - ./config:/config:z
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "100"
    environment:
      VIRTUAL_HOST: filebrowser.arpa
