---
- name: Enable Windows Subsystem Linux 2 (WSL2)
  ansible.windows.win_powershell:
    script: |
      echo "Beginning Provisioning of Windows Server"

- name: Set DNS Servers of Windows Server
  ansible.windows.win_powershell:
    script: |
      Write-Host "Setting DNS for Windows"

- name: Run PowerShell script with parameters
  ansible.windows.win_powershell:
    script: |
      Write-Host "Enabling WSL2"
      Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux -NoRestart
      $Path = $env:TEMP;
      $Ubuntu_Installer = "Ubuntu.appx";
      Invoke-WebRequest -Uri "https://aka.ms/wslubuntu2004" -OutFile $Path\$Ubuntu_Installer -UseBasicParsing;
      Add-AppxPackage .\$Ubuntu_Installer
      Remove-Item $Path\$Ubuntu_Installer
      ubuntu config --default-user root
      Write-Host "WSL2 Enabled Successfully"

- name: Install Python and Ansible on Windows Jumphost
  ansible.windows.win_powershell:
    script: |
      Write-Host "Installing Python"
      $Path = $env:TEMP;
      $Installer = "python_installer.exe";
      if (Test-Path -Path $Path\$Installer -PathType Leaf) {
        Write-Host "Python already downloaded!"
      }
      else {
        Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.8.5/python-3.8.5-amd64.exe" -OutFile $Path\$Installer;
        #Invoke-WebRequest -Uri "https://github.com/serwy/tkthread/files/4258625/thread2.8.4.zip" -OutFile "C:/temp/tkthread.zip"
      }
      Start-Process -FilePath $Path\$Installer -Args "/quiet InstallAllUsers=1 PrependPath=1 Include_test=0" -Verb RunAs -Wait;
      $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
      python -m pip install --upgrade pip
      Remove-Item -r $Path\$Installer
      ansible-galaxy collection install ansible.windows
      Write-Host "Python Environment Installed Successfully"
      python -m pip install ansible
      ansible-galaxy collection install ansible.windows
      Write-Host "Ansible Installed Successfully"

- name: Download Images/OVFs
  ansible.windows.win_powershell:
    script: |
      Invoke-WebRequest '{{ srs_download_link }}' -OutFile c:\google.html

- name: Extract/Expand Images
  ansible.windows.win_powershell:
    script: |
      $destinationUnzipPath=C:\TEMP
      $zipfilePath=C:\TEMP
      sz x -o$destinationUnzipPath $zipfilePath -r ;