---
version: "3.9"
services:
  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=yacht.arpa
      - VIRTUAL_PORT=8000
    ports:
      - 8000:8000
    volumes:
      - yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  yacht:
