version: '3.5'

networks:
  default:
    name: webproxy

services:
  transmission-openvpn:
    image: haugene/transmission-openvpn:latest
    volumes:
      - /home/${USER}/Torrents/:/data
      - ./config:/config
    networks:
      - private-network
    environment:
      - PUID=1000
      - PGID=1000
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --dhcp-option DNS 9.9.9.9
      - CREATE_TUN_DEVICE=true
      - VIRTUAL_HOST=transmission.arpa
      - VIRTUAL_PORT=9091
    env_file:
      - .env
    devices:
      - /dev/net/tun
    logging:
      driver: json-file
      options:
        max-size: 10m
    expose:
      - 9091
      - 8888
    ports:
      - 9091:9091
      - 8888:8888
    cap_add:
      - NET_ADMIN
    dns:
      - 1.1.1.1

