version: '3.9'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab'
    container_name: gitlab
    logging:
      options:
        max-size: "10m"
        max-file: "100"
    environment:
      VIRTUAL_HOST: gitlab.arpa
      VIRTUAL_PORT: 80
      GITLAB_PORT: 80
      EXTERNAL_URL: "http://gitlab.arpa"
      COMPOSE_HTTP_TIMEOUT: 300
    extra_hosts:
      - "gitlab.arpa:192.168.1.60:8929"
    ports:
      - '8929:80'
    volumes:
      - '/apps/gitlab/config:/etc/gitlab'
      - '/apps/gitlab/logs:/var/log/gitlab'
      - '/apps/gitlab/data:/var/opt/gitlab'
