version: '3.7'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'localhost'
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['initial_root_password'] = 'GitLabIsFun'
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - '/home/mrdr/Containers/gitlab/config:/etc/gitlab'
      - '/home/mrdr/Containers/gitlab/logs:/var/log/gitlab'
      - '/home/mrdr/Containers/gitlab/data:/var/opt/gitlab'
    networks:
      - gitlab
#  gitlab-runner:
#    image: gitlab/gitlab-runner:alpine
#    container_name: gitlab-runner
#    restart: always
#    depends_on:
#      - web
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - '/home/mrdr/Containers/gitlab/gitlab-runner:/etc/gitlab-runner'
#    networks:
#      - gitlab

networks:
  gitlab:
    name: gitlab-network
