version: '3.9'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab'
    container_name: gitlab
    environment:
      VIRTUAL_HOST: gitlab.arpa
      VIRTUAL_PORT: 80
      GITLAB_PORT: 8929
      COMPOSE_HTTP_TIMEOUT: 300
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.arpa'
        gitlab_rails['initial_root_password'] = 'GitLabIsFun'
    ports:
      - '8929:80'
    volumes:
      - '/apps/gitlab/config:/etc/gitlab'
      - '/apps/gitlab/logs:/var/log/gitlab'
      - '/apps/gitlab/data:/var/opt/gitlab'

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    depends_on:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - '/apps/gitlab/gitlab-runner:/etc/gitlab-runner'
