version: '3.9'

services:
  postgres:
    image: postgres:15.4
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      VIRTUAL_HOST: postgres.arpa
      VIRTUAL_PORT: 5432
    ports:
      - "5432:5432"

