version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      VIRTUAL_HOST: postgres.arpa
      VIRTUAL_PORT: 5432
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - VIRTUAL_HOST=adminer.arpa
      - VIRTUAL_PORT=8080
    ports:
      - "8282:8080"