version: '3.9'
services:
  cockpit:
    image: markdegroot/cockpit-ubuntu
    container_name: cockpit
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - "8080:9090"
    environment:
      VIRTUAL_HOST: "r510.arpa"
      VIRTUAL_PORT: "8080"
    privileged: true