services:
    db:
        image: 'mongo:latest'
        volumes:
        - 'mongo-vol:/data/db'
        networks:
        - yournetwork
    cms:
        image: agentejo/cockpit
        environment:
            COCKPIT_SESSION_NAME: cockpit
            COCKPIT_SALT: _create_your_own_
            COCKPIT_DATABASE_SERVER: 'mongodb://db:27017'
            COCKPIT_DATABASE_NAME: cockpit_master
        depends_on:
        - db
        ports:
        - "8080:80"
        networks:
        - yournetwork
    networks:
    yournetwork:
        driver: bridge
    volumes:
    mongo-vol: null
