# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
http:
  use_x_forwarded_for: true
  trusted_proxies:
  - 192.168.1.60
  - 127.0.0.1
  ip_ban_enabled: true
  login_attempts_threshold: 5
