version: "3.9"
services:
   adguardhome:
     image: adguard/adguardhome
     container_name: adguardhome
     ports:
       - "53:53/tcp"
       - "53:53/udp"
       - "67:67/udp"
       - "68:68/udp"
       - "443:443/udp"
       - "443:443/tcp"
       - "853:853/tcp"
       - "853:853/udp"
       - "8853:8853/udp"
       - "5443:5443/tcp"
       - "5443:5443/udp"
       - "3000:3000/tcp"
       - "82:82/tcp"
     environment:
      - VIRTUAL_HOST=adguard.arpa
      - VIRTUAL_PORT=3000
     volumes:
       - ./work:/opt/adguardhome/work
       - ./conf:/opt/adguardhome/conf