version: "2"
services:
   adguardhome:
     image: adguard/adguardhome
     container_name: adguardhome
     ports:
       - 2553:53
       - 784:784/udp
       - 853:853/tcp
       - 3000:3000/tcp
       - 83:80/tcp
     environment:
      - VIRTUAL_HOST=adguard.arpa
      - VIRTUAL_PORT=3000
     volumes:
       - ./work:/opt/adguardhome/work
       - ./conf:/opt/adguardhome/conf