version: "2"
services:
   adguardhome:
     image: adguard/adguardhome
     container_name: adguardhome
     ports:
       - 192.168.1.62:53:53/tcp
       - 192.168.1.62:53:53/udp
       - 784:784/udp
       - 853:853/tcp
       - 3000:3000/tcp
       - 83:80/tcp
     volumes:
       - ./work:/opt/adguardhome/work
       - ./conf:/opt/adguardhome/conf