version: '3.9'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    network_mode: host
    ports:
      - "90:80"
    volumes:
      - ./vhost.d:/etc/nginx/vhost.d
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock
    restart: unless-stopped
