version: '3.9'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf**:ro
      - ./certs:/etc/nginx/certs
    restart: unless-stopped

networks:
  webproxy:
    name: webproxy
