version: "3.9"
services:
  baserow:
    container_name: baserow
    image: baserow/baserow:latest
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      BASEROW_PUBLIC_URL: 'https://baserow.heavenhomestead.com'
      VIRTUAL_HOST: "baserow.arpa"
      VIRTUAL_PORT: "8280"
    ports:
      - "8280:80"
      - "8442:443"
    volumes:
      - baserow_data:/baserow/data
    restart: unless-stopped

volumes:
  baserow_data:
