version: "3.4"
services:
  baserow:
    container_name: baserow
    image: baserow/baserow:latest
    environment:
      BASEROW_PUBLIC_URL: 'http://baserow.arpa'
      VIRTUAL_HOST: baserow.arpa
      VIRTUAL_PORT: 8090
    ports:
      - "8090:8090"
    volumes:
      - baserow_data:/baserow/data
    restart: unless-stopped

volumes:
  baserow_data:
