version: "3.9"
services:
  baserow:
    container_name: baserow
    image: baserow/baserow:latest
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      BASEROW_PUBLIC_URL: 'http://baserow.arpa'
      VIRTUAL_HOST: baserow.arpa
    volumes:
      - baserow_data:/baserow/data
    restart: unless-stopped

volumes:
  baserow_data:
