version: "3.4"
services:
  baserow:
    container_name: baserow
    image: baserow/baserow:latest
    environment:
      BASEROW_PUBLIC_URL: 'http://192.168.1.60'
      VIRTUAL_HOST: baserow.arpa
      VIRTUAL_PORT: 9090
    ports:
      - "9090:9090"
    volumes:
      - baserow_data:/baserow/data
    restart: unless-stopped

volumes:
  baserow_data:
