version: "3.4"
services:
  baserow:
    container_name: baserow
    image: baserow/baserow:1.13.0
    environment:
      BASEROW_PUBLIC_URL: 'http://baserow.home.arpa'
      VIRTUAL_HOST: baserow.home.arpa
      VIRTUAL_PORT: 80
    ports:
      - 80
    volumes:
      - baserow_data:/baserow/data
volumes:
  baserow_data:

networks:
  default:
    external:
      name: internal
