---
version: '3.9'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    volumes:
      - /apps/jellyfin/config:/config
      - /apps/jellyfin/cache:/cache
      - /media/media/Movies:/movies
      - /media/media/TV:/tv
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.1.60
      - TRUST_DOWNSTREAM_PROXY=true
      - VIRTUAL_HOST=jellyfin.arpa
      - VIRTUAL_PORT=8096
    ports:
      - "8096:8096"
