---
version: '3.9'
services:
  jellyfin:
    image: jellyfin/jellyfin:10.8.10 #10.8.1 last stable.
    container_name: jellyfin
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    user: 1000:1000
    volumes:
      - /apps/jellyfin/config:/config
      - /apps/jellyfin/cache:/cache
      - /media/media/Movies:/movies
      - /media/media/TV:/tv
      - /media/media/Comics:/comics
      - /media/media/Books:/books
      - /media/media/Music:/music
      - /media/photos:/photos
      - /dev/shm:/transcodes:rw
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.1.60
      - TRUST_DOWNSTREAM_PROXY=true
      - VIRTUAL_HOST=jellyfin.arpa
      - VIRTUAL_PORT=8096
    ports:
      - "8096:8096"
