---
version: '3.9'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    networks:
      - webproxy
    volumes:
      - /apps/jellyfin/config:/config
      - /apps/jellyfin/cache:/cache
      - /media/media/Movies:/movies:ro
      - /media/media/TV:/tv:ro
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.1.60
      - TRUST_DOWNSTREAM_PROXY=true
      - VIRTUAL_HOST=jellyfin.arpa
      #- VIRTUAL_PORT=8096

networks:
  webproxy:
    name: webproxy
