---
version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    networks:
      - webproxy
    volumes:
      - /apps/jellyfin/config:/config
      - /apps/jellyfin/cache:/cache
      - /media/media/Movies:/movies:ro
      - /media/media/TV:/tv:ro
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin.arpa
      - TRUST_DOWNSTREAM_PROXY=true
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.port=8096"
      - "traefik.frontend.rule=Host:jellyfin.arpa"

networks:
  webproxy:
    name: webproxy
