version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=assist.arpa
      - TZ="US/Chicago"
    restart: unless-stopped
    privileged: true
    network_mode: host