---
version: '3.9'

services:
    docker-registry-ui:
        container_name: docker-registry-ui
        image: konradkleine/docker-registry-frontend:latest
        links:
            - docker-registry:docker-registry
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
            - ./certs/frontend.crt:/etc/apache2/server.crt:ro
            - ./certs/frontend.key:/etc/apache2/server.key:ro
        environment:
            - USE_SSL=no
            - ENV_DOCKER_REGISTRY_HOST=docker-registry.arpa
            - ENV_DOCKER_REGISTRY_PORT=5000
            - ENV_DOCKER_REGISTRY_USE_SSL=0
            - VIRTUAL_HOST=docker-registry.arpa
            - VIRTUAL_PORT=8443
        restart: unless-stopped

    docker-registry:
        container_name: docker-registry
        image: registry:latest
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: registry.arpa
            VIRTUAL_PORT: 5000
        volumes:
            - ./volume:/var/lib/registry:rw
            - ./registry/config:/etc/docker/registry:ro
            - ./registry/storage:/var/lib/registry:rw
            - ./registry/certs:/certs:ro
        ports:
            - "5000:5000"
