---
version: '3.9'

services:

    docker-registry-ui:
        container_name: docker-registry-ui
        image: konradkleine/docker-registry-frontend:v2
        #build: ../
        links:
            - docker-registry:docker-registry
        ports:
            # Publish the frontend's port 443 on the IP 0.0.0.0 on port 8443
            - "0.0.0.0:8443:443"
        volumes:
            - ./certs/frontend.crt:/etc/apache2/server.crt:ro
            - ./certs/frontend.key:/etc/apache2/server.key:ro
        environment:
            # The front-end is SSL protected
            - ENV_USE_SSL=no
            - ENV_DOCKER_REGISTRY_HOST=docker-registry.arpa
            - ENV_DOCKER_REGISTRY_PORT=5000
            # The registry is SSL protected as well
            - ENV_DOCKER_REGISTRY_USE_SSL=0
            - VIRTUAL_HOST=docker-registry.arpa
            - VIRTUAL_PORT=8443
        restart: unless-stopped

    # Setup registry
    docker-registry:
        container_name: docker-registry
        image: registry:2.2.0
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: registry.arpa
            VIRTUAL_PORT: 5000
        volumes:
            # Mount the config directory
            - ./registry/config:/etc/docker/registry:ro
            # Make the registry storage persistent (see ./config/config.yml for the path)
            - ./registry/storage:/var/lib/registry:rw
            # Mount our own certificate and key
            - ./registry/certs:/certs:ro
        ports:
            # Publish registry's port 5000 on the IP 0.0.0.0 on port 5000
            - "0.0.0.0:5000:5000"
