---
version: '3.9'

services:
  docker-registry:
    container_name: docker-registry
    image: registry:2
    ports:
      - 5000:5000
    restart: always
    environment:
      VIRTUAL_HOST: registry.arpa
      VIRTUAL_PORT: 5000
    volumes:
      - /apps/docker_registry/volume:/var/lib/registry

  docker-registry-ui:
    container_name: docker-registry-ui
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 8005:80
    environment:
      ENV_DOCKER_REGISTRY_HOST: docker-registry
      ENV_DOCKER_REGISTRY_PORT: 5000
      VIRTUAL_HOST: docker.arpa