version: "3.9"
services:
  serge:
    restart: on-failure
    build: 
      context: .
      dockerfile: Dockerfile
    #command: serge python3 /usr/src/app/api/utils/download.py tokenizer 7B
    volumes:
      - datadb:/data/db
      - weights:/usr/src/app/weights/
      - /etc/localtime:/etc/localtime:ro 
    ports:
      - "8008:8008"

volumes:
  datadb:
  weights: