version: '1.0'
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - SERVERPORT=51820
      - PEERS=3
      - PEERDNS=auto
      - ALLOWEDIPS=0.0.0.0/0
      - INTERNAL_SUBNET=10.13.13.0/24 # Subnet used in VPN tunnel
      - SERVERURL=${SERVERURL} # Wireguard VPN server address
      - FILE__PASSWORD=${WORKDIR}/password.txt
    volumes:
      - ${WORKDIR}/wireguard:/services
      - /opt/wireguard-server/config:/config
      - /usr/src:/usr/src # location of kernel headers
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always

  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ${WORKDIR}/ddclient:/config
    restart: always
