version: '3.9'
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    hostname: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - PEERS=9
      - PEERDNS=192.168.1.60
      - ALLOWEDIPS=0.0.0.0/0
      - INTERNAL_SUBNET=10.13.13.0/24 # Subnet used in VPN tunnel
      - COMPOSE_HTTP_TIMEOUT=300
    env_file:
      - .env
    volumes:
      - /opt/wireguard-server/config:/config
      - /usr/src:/usr/src # location of kernel headers
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    dns:
      - 192.168.1.60
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
