version: '3.9'

networks:
  webproxy:
    name: webproxy

services:
  dns:
    restart: always
    image: jpillora/dnsmasq
    hostname: 'dnsmasq'
    container_name: 'dnsmasq'
    environment:
      HTTP_USER: admin
      HTTP_PASSWORD: Test123
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    networks:
      - webproxy