version: '3.9'

services:
  runner:
    build: .
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped