# docker run -v /mnt:/mnt -it ubuntu
FROM ubuntu:latest
RUN apt install -y mkvtoolnix atomicparsley mediainfo rename ffmpeg python3 python3-pip
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install youtube-dl
