version: '3.9'

services:
  pgvector:
    image: ankane/pgvector
    container_name: pgvector
    hostname: pgvector
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      VIRTUAL_HOST: pgvector.arpa
      VIRTUAL_PORT: 5430
    ports:
      - "5430:5432"
