version: '3.9'

services:
  pgvector:
    image: ankane/pgvector
    container_name: pgvector
    hostname: pgvector
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: "postgres"
      VIRTUAL_HOST: pgvector.arpa
      VIRTUAL_PORT: 5432
    ports:
      - "5432:5432"
