---
version: '3.9'

services:
  server_fan_speed:
    build: .
    container_name: server_fan_speed
    privileged: true
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - /dev/ipmi0:/dev/ipmi0
    restart: unless-stopped
