version: "3"

services:
  pihole:
    depends_on: [unbound]
    container_name: pihole
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
      - 10.2.0.200 # Points to unbound
    environment:
      - PIHOLE_DNS_=1.1.1.1
      - DHCP_ACTIVE=false
      - ServerIP=10.2.0.100 # Internal IP of pihole
      - DNS1=10.2.0.200 # Unbound IP
      - DNS2=10.2.0.200 # If we don't specify two, it will auto pick google.
    volumes:
      - '/services/etc-pihole:/etc/pihole'
      - '/services/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: always
    networks:
      private_network:
        ipv4_address: 10.2.0.100