version: '3.9'
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: always
    deploy:
      mode: replicated
      replicas: 3
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /apps/gitlab-runner/config:/etc/gitlab-runner
      - /apps/gitlab-runner/docker-machine-config:/root/.docker/machine
      - docker-machine-config:/root/.docker/machine