version: '3.9'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - MARIADB_ROOT_PASSWORD=example
      - VIRTUAL_HOST=mariadb.arpa
      - VIRTUAL_PORT=3306

  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - VIRTUAL_HOST=adminer.arpa
      - VIRTUAL_PORT=8080
    ports:
      - 8282:8080