version: "3"

networks:
  dns_network:
    ipam:
      driver: bridge
      config:
        - subnet: 172.20.0.0/16

services:
  unbound:
    image: mvance/unbound-rpi:latest
    container_name: unbound
    restart: always
    hostname: unbound
    volumes:
      - ./unbound:/opt/unbound/etc/unbound/
    ports:
      - 5053:5053/tcp
      - 5053:5053/udp
    healthcheck:
      disable: true
    networks:
      dns_network:
        ipv4_address: 172.20.0.7

  wireguard:
    depends_on: [unbound, pihole]
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - PEERS=9
      - PEERDNS=172.20.0.6
      - ALLOWEDIPS=0.0.0.0/0
      - INTERNAL_SUBNET=10.13.13.0/24 # Subnet used in VPN tunnel
    env_file:
      - .env
    volumes:
      - /opt/wireguard-server/config:/config
      - /usr/src:/usr/src # location of kernel headers
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    dns:
      - 172.20.0.6 # Points to pihole
      - 172.20.0.7 # Points to unbound
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
    networks:
      dns_network:
        ipv4_address: 172.20.0.8

  pihole:
    depends_on: [unbound]
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - yy.yy.yy.yy:53:53/tcp
      - yy.yy.yy.yy:53:53/udp
      - 80:80/tcp
      - 443:443/tcp
    dns:
      - 127.0.0.1
      - 172.20.0.7 # Points to unbound
    environment:
      - PIHOLE_DNS_=1.1.1.1
      - DHCP_ACTIVE=false
      - ServerIP=172.20.0.6 # Internal IP of pihole
      - DNS1=172.20.0.7 # Unbound IP
      - DNS2=172.20.0.7 # If we don't specify two, it will auto pick google.
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/services/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: always
    networks:
      dns_network:
        ipv4_address: 172.20.0.6
