---
version: "3"
services:
  unbound:
    image: "mvance/unbound:latest"
    container_name: unbound
    restart: always
    hostname: "unbound"
    environment:
      - COMPOSE_HTTP_TIMEOUT=300
    volumes:
      - "./unbound:/opt/unbound/etc/unbound/"
