---
version: "3.9"

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - COMPOSE_HTTP_TIMEOUT=300
      - VIRTUAL_HOST=heimdall.arpa
    volumes:
      - /services/heimdall/config:/config
    ports:
      - 8093:80
      - 8443:443
    restart: unless-stopped
