---
version: "2.1"

networks:
  default:
    name: webproxy

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    networks:
      - webproxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - COMPOSE_HTTP_TIMEOUT=300
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`heimdall.arpa`)"
      - "traefik.http.routers.heimdall.entrypoints=web"
      - "traefik.port=80"
    volumes:
      - /services/heimdall/config:/config
    ports:
      - 8080:80
      - 443:443
    restart: always
