version: "3"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.3.0.0/24

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000
    networks:
      private_network:
        ipv4_address: 10.3.0.10

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    hostname: uptime
    env_file:
      - .env
    volumes:
      - /services/uptime-kuma-data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.3.0.90

  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    hostname: transmission
    volumes:
      - /mnt/Torrents/:/data
    environment:
      - PUID=1000
      - PGID=1000
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    env_file:
      - .env
    devices:
      - /dev/net/tun
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
      - 8888:8888
    cap_add:
      - NET_ADMIN
    dns:
      - 10.2.0.100 # Points to pihole
      - 10.2.0.200 # Points to unbound
    networks:
      private_network:
        ipv4_address: 10.3.0.20

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - JELLYFIN_PublishedServerUrl=192.168.1.5 #optional
    env_file:
      - .env
    volumes:
      - /services:/config
      - /path/to/tvseries:/data/tvshows
      - /path/to/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.3.0.30

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    hostname: heimdall
    environment:
      - PUID=1000
      - PGID=1000
    env_file:
      - .env
    volumes:
      - ./config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.3.0.40

  gitlab-web:
    image: 'gitlab/gitlab-ce:latest'
    restart: unless-stopped
    hostname: gitlabteam
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['initial_root_password'] = 'GitLabIsFun'
    env_file:
      - .env
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    networks:
      private_network:
        ipv4_address: 10.3.0.50

  directus-database:
    container_name: directus-database
    hostname: directusd
    image: postgis/postgis:13-master
    env_file:
      - .env
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      private_network:
        ipv4_address: 10.3.0.60

  directus-cache:
    container_name: directus-cache
    hostname: directuscache
    image: redis:6
    env_file:
      - .env
    networks:
      private_network:
        ipv4_address: 10.3.0.70

  directus-web:
    container_name: directus-web
    hostname: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
    networks:
      private_network:
        ipv4_address: 10.3.0.80
    depends_on:
      - directus-cache
      - directus-database
    environment:
      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'
      PUBLIC_URL: 'https://directus.knux.com'
    env_file:
      - .env