version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    environment:
      VIRTUAL_HOST: 'uptime-kuma.arpa'
      VIRTUAL_PORT: '3001'
    volumes:
      - /services/uptime-kuma-data:/app/data
    ports:
      - 3001:3001
    restart: always
