version: '3.9'

networks:
  webproxy:
    name: webproxy

services:
  traefik:
    image: traefik
    container_name: traefik
    networks:
      - webproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.toml:/traefik.toml"
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:lab.arpa"