#Comment out when done.
logLevel = "DEBUG"

defaultEntryPoints = ["http","https"]

[web]
  #Run Traefik info page at 8080.
  address = ":8080"

[entryPoints]
  [entryPoints.http]
    #redirect ALL http traffic to https 443
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

#Let's encrypt setup
[acme]
  email = "knucklessg1@gmail.com"
  storage = "acme.json"
  entryPoint = "https"
  #When new host is created, request certificate.
  onHostRule = true
  [acme.httpChallenge]
    entryPoint = "http"

#Watch Docker, when new containers are created with label create mapping.
[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "lab.arpa"
  watch = true