---
version: '3.9'

services:
  cloudflared:
    image: "cloudflare/cloudflared:latest"
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - TOKEN
    restart: "unless-stopped"
