---
version: '3.9'

services:
  cloudflared:
    image: "cloudflare/cloudflared:latest"
    env_file:
      - token.env
    command:
      - echo
      - "$${TOKEN}";
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - $${TOKEN}
    restart: "unless-stopped"
